image: docker:latest

stages:
- build
- publish
- deploy

variables:
  DOCKER_IMG: "galacticfog/kong"
  LEGACY_CI_URL: "https://gtw1.demo.galacticfog.com/ci/legacy-ci"
  VERSION: "release-2.3.8"
  REPOSITORY_NAME: "docker-kong"
  MASTER_BRANCH_NAME: "0.10.3-better-config"
  PROVIDER_TYPE: "Kong"

docker-build-and-publish:
  stage: build
  services:
    - docker:dind
  script:
    # - echo "Install Dependencies:"
    # - apk add --update --no-cache bash gawk sed grep curl wget git jq tar
    - echo "Login Docker Registry:"
    - echo ${DOCKER_PWD} | docker login ${DOCKER_REGISTRY} --username ${DOCKER_USER} --password-stdin
    - echo "Build and Publish Docker Image:"
    - echo "================================="
    - cat Dockerfile
    - echo "================================="
    - DOCKER_TAG=${CI_BUILD_TAG-$VERSION-${CI_BUILD_REF:0:8}}
    - echo building $DOCKER_IMG:$DOCKER_TAG
    - docker build -t $DOCKER_IMG:$DOCKER_TAG .
    - docker push     $DOCKER_IMG:$DOCKER_TAG
    - |
      if [ ${CI_COMMIT_REF_NAME} == "${MASTER_BRANCH_NAME}" ]; then
         docker tag $DOCKER_IMG:$DOCKER_TAG $DOCKER_IMG:latest
         docker push $DOCKER_IMG:latest
      fi
    - docker rmi      $DOCKER_IMG:$DOCKER_TAG

github-publish:
  image: galacticfog/gitlab-updater
  stage: publish
  script: 
    - git remote remove github || true
    - git remote add github https://$GITHUB_CREDENTIALS@github.com/GalacticFog/${REPOSITORY_NAME}.git
    - |
      if [ -z ${CI_BUILD_TAG} ]; then 
         git push github HEAD:$CI_BUILD_REF_NAME
      else 
         git push -f github $CI_BUILD_TAG
      fi
  only:
    - 0.10.3-better-config
    - tags
  artifacts:

.deploy_template: &deploy_to_test
  image: galacticfog/gitlab-updater
  stage: deploy
  environment: test
  tags: 
    - test-cluster
  script: 
    - DOCKER_TAG=${CI_BUILD_TAG-$VERSION-${CI_BUILD_REF:0:8}}
    - echo "Next publish $CI_URL image=$DOCKER_IMG:$DOCKER_TAG redeploy:=true provider_type=Kong git_ref=$CI_COMMIT_REF_NAME git_sha=$CI_COMMIT_SHA git_author=$GITLAB_USER_NAME"
    - http --check-status -a "$API_KEY":"$API_SECRET" --ignore-stdin $CI_URL image=$DOCKER_IMG:$DOCKER_TAG redeploy:=true provider_type=Kong git_ref=$CI_COMMIT_REF_NAME git_sha=$CI_COMMIT_SHA git_author="$GITLAB_USER_NAME"
  allow_failure: true
  artifacts:
  
auto-deploy-master:
  <<: *deploy_to_test
  allow_failure: false
  only: 
    - ${MASTER_BRANCH_NAME}
    - 0.10.3-better-config

manual-deploy-non-master:
  <<: *deploy_to_test
  allow_failure: true
  except: 
    - ${MASTER_BRANCH_NAME}
  when: manual
